package org.jack.qsport_admin.gui;

import org.jack.qsport.db.Import;
import org.jack.qsport.db.DBAnbindung;
import org.jack.qsport.helper.Persistenz;
import org.jack.qsport.modell.Kurs;
import org.jack.qsport.modell.QSport;
import org.jack.qsport.modell.Semester;
import org.jack.qsport.modell.Sportart;
import org.jack.qsport.modell.Student;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.jack.qsport.pdf.CreatePDF;

/**
 *
 * @author
 * ogarkow.theodor;borst.kilian;schmueck.marius;brust.niklas;kiesel.christoph
 */
public class Hauptfenster extends javax.swing.JFrame {

    QSport qsp = new QSport();
    //ArrayList<Kurs> kurse;

    /**
     * Creates new form Hauptfenster
     */
    public Hauptfenster() {
        //    this.kurse = qsp.getKurseImSemester();
        initComponents();
        //this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        spImport = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_host = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_user = new javax.swing.JTextField();
        jTextField_password = new javax.swing.JTextField();
        jButton_TestVerbindung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spAdd = new javax.swing.JButton();
        spRemove = new javax.swing.JButton();
        jComboBoxSemester = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        spTable = new javax.swing.JTable();
        txtmaxAnzahl = new javax.swing.JTextField();
        jComboBoxSportarten = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonSaveKurs = new javax.swing.JButton();
        jButtonLoadKurs = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        wahlAusDB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGesamtListe = new javax.swing.JTable();
        jButtonZuweisung = new javax.swing.JButton();
        jTabbedEinteilung = new javax.swing.JTabbedPane();
        jPanel11_1 = new javax.swing.JPanel();
        jPanel11_2 = new javax.swing.JPanel();
        jPanel12_1 = new javax.swing.JPanel();
        jPanel12_2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Q Sport: Lehrerprogramm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Start", jPanel1);

        spImport.setText("Import aus ASV");
        spImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spImportActionPerformed(evt);
            }
        });

        jLabel4.setText("Datenbank-Adresse:");

        jTextField_host.setText("jsg-kg.fortiddns.com");
        jTextField_host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hostActionPerformed(evt);
            }
        });

        jLabel5.setText("Benutzer:");

        jLabel6.setText("Passwort:");

        jTextField_user.setText("q11");

        jTextField_password.setText("q11");
        jTextField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_passwordActionPerformed(evt);
            }
        });

        jButton_TestVerbindung.setText("Teste-Verbindung");
        jButton_TestVerbindung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TestVerbindungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_host, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jTextField_password)
                    .addComponent(jTextField_user))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spImport)
                    .addComponent(jButton_TestVerbindung))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton_TestVerbindung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spImport)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(460, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Einstellungen", jPanel4);

        jPanel2.setForeground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Sportarten");

        spAdd.setText("Kurs hinzufügen");
        spAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spAddActionPerformed(evt);
            }
        });

        spRemove.setText("Kurs entfernen");
        spRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spRemoveActionPerformed(evt);
            }
        });

        String[] stringsSemester;
        Semester[] semester =   Semester.values();
        stringsSemester = new String[semester.length];
        for(int i=0; i<stringsSemester.length;i++){
            stringsSemester[i] = semester[i].toString();
        }
        jComboBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(stringsSemester));
        jComboBoxSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSemesterActionPerformed(evt);
            }
        });

        spTable.setBackground(new java.awt.Color(240, 240, 240));
        spTable.setModel(new TableModelKurse(qsp.getKurse()));
        spTable.setName(""); // NOI18N
        jScrollPane1.setViewportView(spTable);

        txtmaxAnzahl.setText("28");

        String[] stringsNamen;
        org.jack.qsport.modell.Sportart[] namen =   org.jack.qsport.modell.Sportart.values();
        stringsNamen = new String[namen.length];
        for(int i=0; i<stringsNamen.length;i++){
            stringsNamen[i] = namen[i].toString();
        }
        jComboBoxSportarten.setModel(new javax.swing.DefaultComboBoxModel<>(stringsNamen));
        jComboBoxSportarten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSportartenActionPerformed(evt);
            }
        });

        jLabel7.setText("Semester");

        jLabel10.setText("Maximal");

        jButtonSaveKurs.setText("Save");
        jButtonSaveKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveKursActionPerformed(evt);
            }
        });

        jButtonLoadKurs.setText("Load");
        jButtonLoadKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadKursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(spAdd)
                                .addGap(33, 33, 33)
                                .addComponent(spRemove))
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxSportarten, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmaxAnzahl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSaveKurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLoadKurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 225, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSportarten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmaxAnzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveKurs))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spAdd)
                    .addComponent(spRemove)
                    .addComponent(jButtonLoadKurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kurse", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        wahlAusDB.setText("Hole Wahl aus DB");
        wahlAusDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wahlAusDBActionPerformed(evt);
            }
        });

        jTableGesamtListe.setModel(new TableModelGesamtListe(qsp.getListeStudent()));
        jScrollPane2.setViewportView(jTableGesamtListe);

        jButtonZuweisung.setText("Zuweisung");
        jButtonZuweisung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZuweisungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wahlAusDB)
                    .addComponent(jButtonZuweisung))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(wahlAusDB)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonZuweisung)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Algorithmus", jPanel3);

        jTabbedEinteilung.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedEinteilungFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTabbedEinteilungFocusLost(evt);
            }
        });

        jPanel11_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel11_1FocusGained(evt);
            }
        });
        jPanel11_1.setLayout(new java.awt.GridLayout(1, 10));
        jTabbedEinteilung.addTab("11-1", jPanel11_1);

        javax.swing.GroupLayout jPanel11_2Layout = new javax.swing.GroupLayout(jPanel11_2);
        jPanel11_2.setLayout(jPanel11_2Layout);
        jPanel11_2Layout.setHorizontalGroup(
            jPanel11_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel11_2Layout.setVerticalGroup(
            jPanel11_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jTabbedEinteilung.addTab("11-2", jPanel11_2);

        javax.swing.GroupLayout jPanel12_1Layout = new javax.swing.GroupLayout(jPanel12_1);
        jPanel12_1.setLayout(jPanel12_1Layout);
        jPanel12_1Layout.setHorizontalGroup(
            jPanel12_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel12_1Layout.setVerticalGroup(
            jPanel12_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jTabbedEinteilung.addTab("12-1", jPanel12_1);

        javax.swing.GroupLayout jPanel12_2Layout = new javax.swing.GroupLayout(jPanel12_2);
        jPanel12_2.setLayout(jPanel12_2Layout);
        jPanel12_2Layout.setHorizontalGroup(
            jPanel12_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel12_2Layout.setVerticalGroup(
            jPanel12_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jTabbedEinteilung.addTab("12-2", jPanel12_2);

        jTabbedPane1.addTab("Einteilung", jTabbedEinteilung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Speichern der Einstellungen

    }//GEN-LAST:event_formWindowClosing

    private void jButtonLoadKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadKursActionPerformed
        // TODO add your handling code here:
        //Persistenz pst = new Persistenz(qsp);
        //qsp = pst.read();
        System.out.println("Hole die Ergebnisse der Wahl");
        String host = jTextField_host.getText();
        String user = jTextField_user.getText();
        String password = jTextField_password.getText();
        DBAnbindung db = new DBAnbindung(host, user, password);
        qsp.setKurse(db.holeKurse());
        qsp.sortiereKurse();
        spTable.setModel(new TableModelKurse(qsp.getKurse()));
        spTable.revalidate();
    }//GEN-LAST:event_jButtonLoadKursActionPerformed

    private void jButtonSaveKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveKursActionPerformed
        // TODO add your handling code here:
        Persistenz pst = new Persistenz(qsp);
        pst.save();
    }//GEN-LAST:event_jButtonSaveKursActionPerformed

    private void jComboBoxSportartenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSportartenActionPerformed
        jComboBoxSemester.setSelectedItem(Sportart.valueOf(jComboBoxSportarten.getSelectedItem().toString()).getArt().toString());
    }//GEN-LAST:event_jComboBoxSportartenActionPerformed

    private void jComboBoxSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSemesterActionPerformed

    private void spRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spRemoveActionPerformed
        Kurs k = (Kurs) qsp.getKurse().get(spTable.getSelectedRow());
        qsp.getKurse().remove(k);
        qsp.sortiereKurse();
        spTable.revalidate();
        System.out.println("Vorhandene Kurse:");
        for (Kurs kurs : qsp.getKurse()) {
            System.out.println(kurs);
        }
    }//GEN-LAST:event_spRemoveActionPerformed

    private void spAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spAddActionPerformed
        Sportart sa = Sportart.valueOf(jComboBoxSportarten.getSelectedItem().toString());
        Semester sem = Semester.valueOf(jComboBoxSemester.getSelectedItem().toString());
        int spMax = Integer.parseInt(txtmaxAnzahl.getText());
        Kurs k = new Kurs(sa, sem, spMax, 0);
        qsp.getKurse().add(k);
        qsp.sortiereKurse();
        spTable.revalidate();
        System.out.println(k);
    }//GEN-LAST:event_spAddActionPerformed

    private void jButton_TestVerbindungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TestVerbindungActionPerformed
        String host = jTextField_host.getText();
        String user = jTextField_user.getText();;
        String password = jTextField_password.getText();
        DBAnbindung db = new DBAnbindung(host, user, password);
        db.testeVerbindung();
    }//GEN-LAST:event_jButton_TestVerbindungActionPerformed

    private void jTextField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_passwordActionPerformed

    private void spImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spImportActionPerformed
        String host = jTextField_host.getText();
        String user = jTextField_user.getText();
        String password = jTextField_password.getText();
        String message = "Achtung!\n" + "Neuer Import löscht alle eingegebenen Daten";
        int dialogButton = JOptionPane.YES_NO_OPTION;
        String[] options = new String[2];
        options[0] = new String("Import");
        options[1] = new String("Cancel");
        int antwort = JOptionPane.showOptionDialog(null, message, "Warnung!", 0, JOptionPane.INFORMATION_MESSAGE, null, options, null);
        if (antwort == JOptionPane.YES_OPTION) {
            DBAnbindung db = new DBAnbindung(host, user, password);
            Import imp = new Import(db);
            imp.schreibeInDB();
        }
    }//GEN-LAST:event_spImportActionPerformed

    private void jTabbedEinteilungFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedEinteilungFocusGained
        // TODO add your handling code here:


    }//GEN-LAST:event_jTabbedEinteilungFocusGained

    private void jTabbedEinteilungFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedEinteilungFocusLost
        jPanel11_1.removeAll();
    }//GEN-LAST:event_jTabbedEinteilungFocusLost

    private void wahlAusDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wahlAusDBActionPerformed
        System.out.println("Hole die Ergebnisse der Wahl");
        String host = jTextField_host.getText();
        String user = jTextField_user.getText();
        String password = jTextField_password.getText();
        DBAnbindung db = new DBAnbindung(host, user, password);
        qsp.setListeStudent(db.holeAlleStudenten());
        jTableGesamtListe.setModel(new TableModelGesamtListe(qsp.getListeStudent()));
        //new CreatePDF(qsp).printJahrgangsWahl();
    }//GEN-LAST:event_wahlAusDBActionPerformed

    private void jButtonZuweisungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZuweisungActionPerformed
        // TODO add your handling code here:
//        ArrayList<Kurs> kurse = qsp.getKurseImSemester(Semester.Q11_1);
//        for(Kurs k: kurse){
//            System.out.println(k);
//        }

        /*
        Einteilung 

         */
        qsp.einteilung(Semester.Q11_1);
        qsp.einteilung(Semester.Q11_2);
        qsp.einteilung(Semester.Q12_1);
        qsp.einteilung(Semester.Q12_2);
        //qsp.einteilung2();

        CreatePDF pdf = new CreatePDF(qsp);
        pdf.printKursVerteilung(Semester.Q11_1);
        pdf.printKursVerteilung(Semester.Q11_2);
        pdf.printKursVerteilung(Semester.Q12_1);
        pdf.printKursVerteilung(Semester.Q12_2);
        pdf.printUebersicht();

        System.out.println("");

        System.out.println("**** Keine Kurse erhalten ******");
        qsp.sortiereSchüler();
        for (Student s : qsp.getListeStudent()) {
            if (s.getAnzahlSemBelegt() < 4) {
                int fehlend = 4 - s.getAnzahlSemBelegt();
                System.out.print("Fehlend: " + fehlend + "Semester  " + s.getName() + ", " + s.getVorname());

                if (s.istImSemester(Semester.Q11_1)) {
                    System.out.print(" " + Semester.Q11_1);
                }
                if (s.istImSemester(Semester.Q11_2)) {
                    System.out.print(" " + Semester.Q11_2);
                }
                if (s.istImSemester(Semester.Q12_1)) {
                    System.out.print(" " + Semester.Q12_1);
                }
                if (s.istImSemester(Semester.Q12_2)) {
                    System.out.print(" " + Semester.Q12_2);
                }

                System.out.println();
            }
        }

        qsp.printBelegung();
    }//GEN-LAST:event_jButtonZuweisungActionPerformed

    private void jTextField_hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hostActionPerformed

    private void jPanel11_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel11_1FocusGained
        // TODO add your handling code here:
        for (Kurs k : qsp.getKurse()) {
            if (k.getSemester() == Semester.Q11_1) {
                System.out.println(k.getSportart() + " " + k.getStudentList().size());
                JScrollPane jsp = new JScrollPane();
                JTable jt = new JTable();
                jt.setModel(new TableModelEinteilung(k.getStudentList()));
                jsp.add(jt);
                jPanel11_1.add(jsp);
                jPanel11_1.revalidate();
            }
        }
    }//GEN-LAST:event_jPanel11_1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hauptfenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hauptfenster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoadKurs;
    private javax.swing.JButton jButtonSaveKurs;
    private javax.swing.JButton jButtonZuweisung;
    private javax.swing.JButton jButton_TestVerbindung;
    private javax.swing.JComboBox<String> jComboBoxSemester;
    private javax.swing.JComboBox<String> jComboBoxSportarten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11_1;
    private javax.swing.JPanel jPanel11_2;
    private javax.swing.JPanel jPanel12_1;
    private javax.swing.JPanel jPanel12_2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedEinteilung;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableGesamtListe;
    private javax.swing.JTextField jTextField_host;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_user;
    public javax.swing.JButton spAdd;
    private javax.swing.JButton spImport;
    public javax.swing.JButton spRemove;
    public javax.swing.JTable spTable;
    public javax.swing.JTextField txtmaxAnzahl;
    private javax.swing.JButton wahlAusDB;
    // End of variables declaration//GEN-END:variables
}
